/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-116556-gcda5f5c5ed-20240809"
#endif /* AVUTIL_FFVERSION_H */
